feat: testing - zacharie.kouadinou

diff --git a/.github/workflows/chocolatine.yml b/.github/workflows/chocolatine.yml
--- a/.github/workflows/chocolatine.yml
+++ b/.github/workflows/chocolatine.yml
@@ -1,95 +1,74 @@
-name: workflows_action
+env:
+  MIRROR_URL: git@github.com:s3gn0n/chocolatine_mirror.git
+  EXECUTABLES: my_sokoban
+name: Github Actions
 on:
   push:
     branches-ignore:
-      - 'ga-ignore-**'
-  pull_request:
-    branches-ignore:
-      - 'ga-ignore-**'
-env:
-  MIRROR_URL: "git@github.com:s3gn0n/chocolatine_mirror.git"
-  EXECUTABLES: "my_sokoban"
-
+      - 'ga-ignore-'
 jobs:
-  current_repository:
-    runs-on: ubuntu-latest
-
-    steps:
-      - name: Check branch name
-        run: |
-          if [ ${{ github.repository }} == "$MIRROR_URL" ]; then
-            echo "Skipping workflow for the mirror repository"
-            exit 78
-          fi
-
   check_coding_style:
-    needs: current_repository
-
+    name: checker
     runs-on: ubuntu-latest
-
     container:
       image: ghcr.io/epitech/coding-style-checker:latest
-
     steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-
-      - name: run coding style checker script
+      - name: checkout_repo
+        uses: actions/checkout@v3
+      - name: check_coding_style
+        run: check.sh $(pwd) $(pwd)
+      - name: display_coding_style_errors
+        run: cat coding-style-reports.log
+      - name: annotation_error
         run: |
-          check.sh . /tmp
-
-      - name: Check for coding style errors
-        run: |
-          content=$(</tmp/coding-style-reports.log)
-          IFS=$'\n'
-          for line in $content; do
-              IFS=":"
-              read -ra parts <<< "$line"
-              for part in "${parts[@]}"; do
-                  echo "$part"
-              done
-          done
+          if grep -q "error" coding-style-reports.log; then
+            echo "::error::$file_content"
+              exit 1
+          fi
 
   check_program_compilation:
-    needs: check_coding_style
-
-    container:
-      image: epitechcontent/epitest-docker:latest
-
+    name: check if program compile
+    needs:
+      - check_coding_style
     runs-on: ubuntu-latest
-
+    container:
+      image: epitechcontent/epitest-docker
     steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: run_make
-        run: |
-          make
-
-      - name: run_make_clean ## checker si cela a généré un exécutable
-        run: |
-          make clean
+      - uses: actions/checkout@v3
+      - id: check_program_compilation
+        run: make
+        timeout-minutes: 2
+      - run: make clean
+      - run: |
+          for FILE in $EXECUTABLES; do
+              if [ ! -e "$FILE" ]; then
+                echo "error : file '$FILE' not exists"
+                exit 1
+              elif [ ! -x "$FILE" ]; then
+                  echo "error : file '$FILE' is not an executable"
+                  exit 2
+              else
+                  echo "$FILE is an executable."
+              fi
+          done
 
   run_tests:
-    needs: check_program_compilation
-
-    container:
-      image: epitechcontent/epitest-docker:latest
-
+    needs:
+      - check_program_compilation
     runs-on: ubuntu-latest
-
+    container:
+      image: epitechcontent/epitest-docker
+    timeout-minutes: 2
     steps:
-      - uses: actions/checkout@v4
-        with:
-          fetch-depth: 0
-      - name: make_test
+      - name: running_test
+        uses: actions/checkout@v3
+      - name: make_test_runs
         run: make tests_run
 
   push_to_mirror:
-    needs: run_tests
-
     runs-on: ubuntu-latest
+    needs : run_tests
+    if : github.event.push
     steps:
       - uses: actions/checkout@v3
         with:
@@ -97,6 +76,6 @@ jobs:
       - uses: pixta-dev/repository-mirroring-action@v1
         with:
           target_repo_url:
-              ${{ env.MIRROR_URL }}
+            $MIRROR_URL
           ssh_private_key:
-              ${{ secrets.GIT_SSH_PRIVATE_KEY }}
+            $GIT_SSH_PRIVATE_KEY
